/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:94d63211-9f29-4d48-8263-21e03c283d36",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_Fh59Vzag6",
    "aws_user_pools_web_client_id": "2npvln9kb3rsl0g7vhkkadhts9",
    "oauth": {},
    "aws_user_files_s3_bucket": "mightydamegatsbybucket143702-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1",
    "aws_cloud_logic_custom": [
        {
            "name": "mightydamegatsbyStripeApi",
            "endpoint": "https://oatann8h4d.execute-api.ca-central-1.amazonaws.com/dev",
            "region": "ca-central-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://6ghakof4yvc4ne4qby6lijq4im.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-l3cebrprczbg5hnkfsy3js5rx4"
};


export default awsmobile;
