/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateUser = /* GraphQL */ `
  subscription OnCreateUser {
    onCreateUser {
      id
      firstName
      lastName
      displayName
      email
      dateRegistered
      userType
      streetAddressOne
      streetAddressTwo
      city
      provinceState
      country
      postalZip
      phone
      subscriber
      dateSubscribed
      createdAt
      updatedAt
      offers {
        id
        offerType
        title
        shortDescription
        longDescription
        keywords
        categories
        price
        salePrice
        mainImageUrl
        otherImageUrls
        available
        brand
        users {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      reviews {
        id
        title
        comment
        rating
        user {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser {
    onUpdateUser {
      id
      firstName
      lastName
      displayName
      email
      dateRegistered
      userType
      streetAddressOne
      streetAddressTwo
      city
      provinceState
      country
      postalZip
      phone
      subscriber
      dateSubscribed
      createdAt
      updatedAt
      offers {
        id
        offerType
        title
        shortDescription
        longDescription
        keywords
        categories
        price
        salePrice
        mainImageUrl
        otherImageUrls
        available
        brand
        users {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      reviews {
        id
        title
        comment
        rating
        user {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
`;
export const onDeleteUser = /* GraphQL */ `
  subscription OnDeleteUser {
    onDeleteUser {
      id
      firstName
      lastName
      displayName
      email
      dateRegistered
      userType
      streetAddressOne
      streetAddressTwo
      city
      provinceState
      country
      postalZip
      phone
      subscriber
      dateSubscribed
      createdAt
      updatedAt
      offers {
        id
        offerType
        title
        shortDescription
        longDescription
        keywords
        categories
        price
        salePrice
        mainImageUrl
        otherImageUrls
        available
        brand
        users {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      reviews {
        id
        title
        comment
        rating
        user {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
`;
export const onCreateOffer = /* GraphQL */ `
  subscription OnCreateOffer {
    onCreateOffer {
      id
      offerType
      title
      shortDescription
      longDescription
      keywords
      categories
      price
      salePrice
      mainImageUrl
      otherImageUrls
      available
      brand
      users {
        id
        firstName
        lastName
        displayName
        email
        dateRegistered
        userType
        streetAddressOne
        streetAddressTwo
        city
        provinceState
        country
        postalZip
        phone
        subscriber
        dateSubscribed
        createdAt
        updatedAt
        offers {
          id
          offerType
          title
          shortDescription
          longDescription
          keywords
          categories
          price
          salePrice
          mainImageUrl
          otherImageUrls
          available
          brand
          createdAt
          updatedAt
        }
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      createdAt
      updatedAt
      reviews {
        id
        title
        comment
        rating
        user {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
`;
export const onUpdateOffer = /* GraphQL */ `
  subscription OnUpdateOffer {
    onUpdateOffer {
      id
      offerType
      title
      shortDescription
      longDescription
      keywords
      categories
      price
      salePrice
      mainImageUrl
      otherImageUrls
      available
      brand
      users {
        id
        firstName
        lastName
        displayName
        email
        dateRegistered
        userType
        streetAddressOne
        streetAddressTwo
        city
        provinceState
        country
        postalZip
        phone
        subscriber
        dateSubscribed
        createdAt
        updatedAt
        offers {
          id
          offerType
          title
          shortDescription
          longDescription
          keywords
          categories
          price
          salePrice
          mainImageUrl
          otherImageUrls
          available
          brand
          createdAt
          updatedAt
        }
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      createdAt
      updatedAt
      reviews {
        id
        title
        comment
        rating
        user {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
`;
export const onDeleteOffer = /* GraphQL */ `
  subscription OnDeleteOffer {
    onDeleteOffer {
      id
      offerType
      title
      shortDescription
      longDescription
      keywords
      categories
      price
      salePrice
      mainImageUrl
      otherImageUrls
      available
      brand
      users {
        id
        firstName
        lastName
        displayName
        email
        dateRegistered
        userType
        streetAddressOne
        streetAddressTwo
        city
        provinceState
        country
        postalZip
        phone
        subscriber
        dateSubscribed
        createdAt
        updatedAt
        offers {
          id
          offerType
          title
          shortDescription
          longDescription
          keywords
          categories
          price
          salePrice
          mainImageUrl
          otherImageUrls
          available
          brand
          createdAt
          updatedAt
        }
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      createdAt
      updatedAt
      reviews {
        id
        title
        comment
        rating
        user {
          id
          firstName
          lastName
          displayName
          email
          dateRegistered
          userType
          streetAddressOne
          streetAddressTwo
          city
          provinceState
          country
          postalZip
          phone
          subscriber
          dateSubscribed
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
`;
export const onCreateReview = /* GraphQL */ `
  subscription OnCreateReview {
    onCreateReview {
      id
      title
      comment
      rating
      user {
        id
        firstName
        lastName
        displayName
        email
        dateRegistered
        userType
        streetAddressOne
        streetAddressTwo
        city
        provinceState
        country
        postalZip
        phone
        subscriber
        dateSubscribed
        createdAt
        updatedAt
        offers {
          id
          offerType
          title
          shortDescription
          longDescription
          keywords
          categories
          price
          salePrice
          mainImageUrl
          otherImageUrls
          available
          brand
          createdAt
          updatedAt
        }
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateReview = /* GraphQL */ `
  subscription OnUpdateReview {
    onUpdateReview {
      id
      title
      comment
      rating
      user {
        id
        firstName
        lastName
        displayName
        email
        dateRegistered
        userType
        streetAddressOne
        streetAddressTwo
        city
        provinceState
        country
        postalZip
        phone
        subscriber
        dateSubscribed
        createdAt
        updatedAt
        offers {
          id
          offerType
          title
          shortDescription
          longDescription
          keywords
          categories
          price
          salePrice
          mainImageUrl
          otherImageUrls
          available
          brand
          createdAt
          updatedAt
        }
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteReview = /* GraphQL */ `
  subscription OnDeleteReview {
    onDeleteReview {
      id
      title
      comment
      rating
      user {
        id
        firstName
        lastName
        displayName
        email
        dateRegistered
        userType
        streetAddressOne
        streetAddressTwo
        city
        provinceState
        country
        postalZip
        phone
        subscriber
        dateSubscribed
        createdAt
        updatedAt
        offers {
          id
          offerType
          title
          shortDescription
          longDescription
          keywords
          categories
          price
          salePrice
          mainImageUrl
          otherImageUrls
          available
          brand
          createdAt
          updatedAt
        }
        reviews {
          id
          title
          comment
          rating
          createdAt
          updatedAt
        }
      }
      createdAt
      updatedAt
    }
  }
`;
